Fixed compatibility issue on `xcompact3d_toolbox.io.Dataset.load_snapshot` when testing if field `is_scalar` on Python 3.8
